name: Generate Terraform README docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read


jobs:
  docs:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@cca78c27ac9e2b6545debf2ecae9df930fd3461c # v1.2.2
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
