name: Terraform Static Code Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-static-analysis.yml'

permissions:
  contents: read

jobs:
  terraform-static-analysis:
    permissions:
      pull-requests: write
    name: Terraform Static Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
    - name: Delete Old Comments
      uses: maheshrayas/action-pr-comment-delete@v3.0
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        org: ministryofjustice
        repo: terraform-github-repository
        user: 'github-actions[bot]' 
        issue: '${{github.event.number}}'
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    - name: Run Analysis
      uses: ministryofjustice/github-actions/terraform-static-analysis@7855159a5c3a9bcd658207c894cc4ed22bd35a22 # v15.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scan_type: single
        tflint_exclude: terraform_unused_declarations
        tfsec_trivy: trivy
        checkov_exclude: CKV_GIT_1
