name: Terraform Unit Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: 
  contents: read

env:
  TF_VAR_github_token: ${{ secrets.TERRAFORM_TEST_ORG_PAT }}
  TF_IN_AUTOMATION: true

jobs:
  terraform-tests:
    name: Run Terraform Python Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # 5.3.0
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Terraform Unit Tests
        run: |
          pytest test/
